spring:
  data:
    mongodb:
      host: mongo-dev.odhome.local
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: otus-spring

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.homework.spring08.changelogs

logging:
  level:
    ROOT: OFF
#    org.springframework: DEBUG
#    org.springframework.transaction: TRACE