spring:
  data:
    mongodb:
      host: mongo-dev.odhome.local
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: otus-spring-11

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.homework.spring11.changelogs

server:
  error:
    include-stacktrace: on_trace_param

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.transaction: INFO
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG