spring:
    batch:
        job:
            enabled: false
    shell:
        interactive:
            enabled: true

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:

    h2:
        console:
            enabled: true
            path: /h2-console
    data:
        mongodb:
            host: mongo-dev.odhome.local
            port: 27017
            authentication-database: admin
            username: admin
            password: admin
            database: otus-spring-14

mongock:
    runner-type: InitializingBean
    change-logs-scan-package:
        - ru.otus.spring.homework.spring14.changelogs

logging:
    level:
        ROOT: INFO
    org.springframework: DEBUG
    org.springframework.transaction: TRACE