DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, GENRE_ID BIGINT, AUTHOR_ID BIGINT, BOOK_NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, GENRE_NAME VARCHAR(255));

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, AUTHOR_NAME VARCHAR(255));

CREATE SEQUENCE AUTHOR_SEQUENCE START WITH 10;
CREATE SEQUENCE BOOK_SEQUENCE START WITH 10;
CREATE SEQUENCE GENRE_SEQUENCE START WITH 10;
